### PR TITLE
Call odom_tf_restart

### PR DESCRIPTION
**Pull request by costashatz**
Use mocap data (see https://github.com/resibots/resibots_launch/pull/2). Tested on the real robot and it works!

### CODE REVIEW

**Comment by dogoepp** [comment]
Does it make sense to call this service if we don't use the motion capture and/or if the odom_transform node is not running ?

**Comment by costashatz** [comment]
> Does it make sense to call this service if we don't use the motion capture and/or if the odom_transform node is not running ?

This only makes sense if you are using visual odometry, motion capture is running and the odom_transform node is running.

So, since service calls are blocking, we need to somehow make sure that it won't get stuck there. One way to do it is to always run odom_transform (i.e. include it in the launch files along with hexa_control). Another one is to convert this service call to a topic and then odom_transform will just listen to this topic and hexa_control will publish (just like robot_localization).

What do you think?

**Comment by dogoepp** [comment]
What about using a ROS parameter which activates the call to the motion 
capture ?

This way, we could also define two roslaunch, one with and the other 
without motion capture.

**Comment by costashatz** [comment]
> What about using a ROS parameter which activates the call to the motion
> capture ?
> 
> This way, we could also define two roslaunch, one with and the other
> without motion capture.

I do not really have a preference. My only second thoughts about this is that we will end up with too many launch files. We already have quite a few (we need to clean them).

**Comment by dogoepp** [comment]
Indeed, it would increase the high number launch files.

I don't know what's best. The other option has the drawback of more 
dependency and seldom used nodes running all the time.

**Comment by costashatz** [comment]
@dogoepp I went for your idea. What do you think? Check also the changes in https://github.com/resibots/resibots_launch/pull/2.

**Comment by dogoepp** [comment]
**OK** to merge

**Pull request merged**
